apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: userservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userservice-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
