---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: userservice-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userservice-pod
  template:
    metadata:
      name: userservice-pod
      labels:
        app: userservice-pod
    spec:
      containers:
        - name: userservice-container
          image: javaexpress/userservice:latest
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-service
spec:
  type: NodePort
  selector:
    app: userservice-pod
  ports:
    - port: 8085 # any port number you can define
      targetPort: 8085
      nodePort: 30002 # using this you can access
...
