---
apiVersion: v1
kind: Pod
metadata:
  name: userservice-pod
  labels :
    app: userservice-pod
spec:
  containers:
    - name: userservice-pod-container
      image: javaexpress/userservice:latest
      ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-service
spec:
  selector:
    app: userservice-pod
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
---