apiVersion: v1
kind: Service
metadata:
  name: userservice-service
spec:
  selector:
    app: userservice-pod
  ports:
    - protocol: TCP
      port: 9090 #outside world
      targetPort: 8085
  type: NodePort