---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
spec:
  selector:
    matchLabels:
      app: userservice-pod
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: userservice-pod
      labels:
        app: userservice-pod
    spec:
      containers:
        - name: user-service-container
          image: 'javaexpress/userservice:1.0.0'
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-service
spec:
  type: LoadBalancer
  selector:
    app: userservice-pod
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
---